namespace ExpectMvc.Models;

/// <summary>
/// A test plan generated by the AI agent from scanned code changes.
/// </summary>
public class TestPlan
{
    public string Id { get; set; } = Guid.NewGuid().ToString("N");
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public string? Description { get; set; }
    public List<TestStep> Steps { get; set; } = new();
    public GitDiff SourceDiff { get; set; } = new();
    public AgentProvider Agent { get; set; } = AgentProvider.Claude;
    public TestTarget Target { get; set; } = TestTarget.Changes;
}

public class TestStep
{
    public int Order { get; set; }
    public string Action { get; set; } = string.Empty;
    public string? Selector { get; set; }
    public string? Value { get; set; }
    public string Expected { get; set; } = string.Empty;
}

public enum AgentProvider
{
    Claude,
    Codex
}

public enum TestTarget
{
    Unstaged,
    Branch,
    Changes
}
